### PR TITLE
JWT OAuth postman collection

### PR DESCRIPTION
**Pull request by Arcgate-Pulkit**
https://sila.atlassian.net/browse/ENGRG-555

### CODE REVIEW

**Comment by johndburk** [comment]
Good work so far. 

All the endpoints in the `Virtual Accounts` folder need to be refactored, they're still pointed at the signer-server.

```http://localhost:{{proxy_port}}/forward?label=get_virtual_accounts```

image

**Comment by johndburk** [comment]
You should also add an updated Postman environment that has:
* app_client_id
* app_client_secret
* jwt_token
and not `_address` (blockchain address) or `_private_key` fields; these will no longer be necessary when using the JWT/`Auth Token` in the future, and removing them from the environment will show any endpoints in the collection that are still using them.

**Comment by Arcgate-Pulkit** [comment]
> ds; these will no longer be necessary when using the JWT/`Auth Token` in the future, and remov

Must have forgotten to save it before exporting 😅
Done though!

**Comment by Arcgate-Pulkit** [comment]
> You should also add an updated Postman environment that has:
> 
> * app_client_id
> * app_client_secret
> * jwt_token
> 
> and take out any `_address` (blockchain address) or `_private_key` fields; these will no longer be necessary when using the JWT/`Auth Token` in the future, and removing them from the environment will show any endpoints in the collection that are still using them.

@johndburk 
I'd surely do it, but before that could you please address the concerns mentioned [here](https://sila.atlassian.net/browse/ENGRG-555?focusedCommentId=101924) on the ticket, so that I'd create it accordingly!

**Comment by johndburk** [comment]
@amack300 this is ready for taking a spin around the block, see what you think.

**Review by amack300 — APPROVED** [review]
Hey @johndburk -

I was able to take a spin around the block via test1 and using postman to validate the following:

- Create JWT App
- Get Auth Token for above app
- Register User to above JWT App via generated Auth Token
- Request KYC
- Check KYC
- Link Bank Account via Plaid
- Issue Sila

That is about as far as I got, but I think this are working great.  QA can likely validate endpoints beyond those but I think things are looking good.  

Thanks!

**Pull request merged**
